### ISSUE TITLE
[리팩토링] @Autowired 걷어내기

### ISSUE THREAD

**Issue by Garamda** [AOMC-Coop/AOMC#5]
@Autowired를 걷어내고 lombok의 @AllArgsConstructor를 사용하여 생성자를 대체하기

**Comment by Garamda** [comment]
인증서버 테스트 후 모든 서버에 적용 예정

**Comment by Garamda** [comment]
인증서버, 파일서버에 적용 완료

lombok의 @AllArgsConstructor 사용을 피해야 한다는 의견이 있었음
(참고 : https://kwonnam.pe.kr/wiki/java/lombok/pitfall)

이에 따라 @Autowired를 생성자로 대체하여 리팩토링 함

채팅 서버에 적용할지는 추후 논의 후 결정할 것

**Comment by leeyunjea** [comment]
좋은 방법 같아요 
필드에 @Autowried를 선언하면 컴파일시에 의존성이 결정되는데 생성자로 의존성 주입을 받으면 컴파일시 의존성이 결정되지 않고 클래스가 만들어질때 의존성이 결정되서 더 좋다고 합니다 :) 👍

**Comment by Garamda** [comment]
https://kwonnam.pe.kr/wiki/java/lombok/pitfall 에서 @AllArgsConstructor와 @RequiredArgsConstructor 를 사용 금지해야 한다는 의견이 있었음. 이를 따라 결국 lombok을 쓰지 않고 생성자를 직접 생성하였으나, 본 프로젝트에 그대로 적용하기에는 상황이 다른 점이 있음

- 링크의 예제에서는 개발자가 객체의 인스턴스를 직접 생성하고 있음
- 그런데 본 프로젝트에서는 사실상 Controller와 Service단에서만 @Autowired를 사용함
- Controller와 Service는 Spring 프레임워크가 주입할 뿐, 개발자가 직접 인스턴스를 생성하는 경우는 없음
- 따라서, 예제에서 제시한 문제가 발생할 경우가 없음

이에 따라 @RequiredArgsConstructor로 생성자를 대체하겠음
